language: python
python:
  - "3.4"
before_install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu saucy main universe"
  - sudo apt-get -qq -y update
  - sudo apt-get install -y iverilog
install:
  - iverilog-vpi --name=vpi/migensim vpi/main.c vpi/ipc.c
  - pip install -r requirements.txt --use-mirrors
script:
  - python setup.py test
notifications:
  email: false
#  irc: "chat.freenode.net#m-labs"
